db:
  image: postgres:latest
  environment:
    - POSTGRES_PASSWORD=project
  restart: always

skills:
  image: dbarysevich/skills:latest
  restart: always
  links:
    - db
  ports:
    - "8080:8080"
  environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=project
    - SERVER_PORT=8080