version: '2'
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/24
services:

  mail:
    image: djfarrelly/maildev
    container_name: skill-mail
    ports:
    - "${MAIL_PORT}:25"
    - "${MAIL_PORT_WEB}:80"

  zookeeper:
    image: skill-zookeeper
    build: ./zookeeper
    ports:
    - "${ZOOKEEPER_PORT}:2181"
    volumes:
    - ${HOST_LOG_DIR}/zookeeper:${CONTAINER_LOG_DIR}

  kafka:
    image: skill-kafka
    build: ./kafka
    ports:
    - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
      KAFKA_ADVERTISED_PORT: "${KAFKA_PORT}"
      KAFKA_ZOOKEEPER_CONNECT: "${DOCKER_IP}:${ZOOKEEPER_PORT}"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
    volumes:
    - ${HOST_LOG_DIR}/kafka:${CONTAINER_LOG_DIR}
    depends_on:
    - zookeeper

  db:
    image: skill-db
    build: ./db
    ports:
    - "${DB_PORT}:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
#    - /tmp/skill/pgdata:${CONTAINER_PG_DATA}
    - ${CONTAINER_PG_DATA}

  mongodb:
    image: skill-mongo
    build: ./mongodb
    ports:
    - "${MONGO_PORT}:27017"
    environment:
    - MONGODB_DATABASE=skills
    - MONGODB_ROOT_USERNAME=root
    - MONGODB_ROOT_PASSWORD=skill
    - MONGODB_ADVERTISED_HOSTNAME=192.168.1.10
    - MONGODB_PRIMARY_PORT_NUMBER=27017
    - MONGODB_REPLICA_SET_KEY=repLocalKey
    - MONGODB_REPLICA_SET_MODE=primary
    - MONGODB_REPLICA_SET_NAME=replocal
    - MONGODB_USERNAME=skill
    - MONGODB_PASSWORD=skill
#    volumes:
#    - ${CONTAINER_MONGO_DATA}
#    command:
#      mongod --auth --replSet 'replocal'

  skill-i18n-service:
    build: ../i18n-service/
    extends:
      file: common-services.yml
      service: default
    ports:
     - "${I18N_SERVICE_PORT}:8080"
    volumes:
    - ${HOST_LOG_DIR}/skill-mail-service:${CONTAINER_LOG_DIR}
    environment:
    - DB_NAME=skill_i18n_service
    depends_on:
    - db
    - kafka

  skill-mail-service:
    build: ../mail-service/
    extends:
      file: common-services.yml
      service: default
    ports:
    - "${MAIL_SERVICE_PORT}:8080"
    volumes:
     - ${HOST_LOG_DIR}/skill-mail-service:${CONTAINER_LOG_DIR}
    environment:
    - _OPTIONS=-Dservices.i18n.url=http://${DOCKER_IP}:${I18N_SERVICE_PORT}
    - DB_NAME=skill_mail_service
    depends_on:
    - db
    - kafka

  skill-authorization-service:
      build: ../authorization-service/
      extends:
        file: common-services.yml
        service: default
      ports:
       - "${AUTHORIZATION_PORT}:8080"
      volumes:
      - ${HOST_LOG_DIR}/skill-authorization-service:${CONTAINER_LOG_DIR}
      environment:
      - DB_NAME=skill_authorization_service
      depends_on:
      - db
      - kafka

  skill-web-service:
    build: ../web-service/
    extends:
      file: common-services.yml
      service: default
    ports:
    - "${WEB_SERVICE_PORT}:8080"
    volumes:
    - ${HOST_LOG_DIR}/skill-mail-service:${CONTAINER_LOG_DIR}
    environment:
    - _OPTIONS=-Dservices.mail.url=http://${DOCKER_IP}:${MAIL_SERVICE_PORT} -Dservices.auth.url=http://${DOCKER_IP}:${AUTHORIZATION_PORT}
    - DB_NAME=skill_web_service
    depends_on:
    - db
    - mongodb
    - kafka
