version: '2'
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/24
services:

  mail:
      image: djfarrelly/maildev
      container_name: skill-mail
      ports:
       - "${MAIL_PORT}:25"
       - "${MAIL_PORT_WEB}:80"

  zookeeper:
      image: skill-zookeeper
      build: ./zookeeper
      ports:
        - "${ZOOKEEPER_PORT}:2181"
      volumes:
        - ${HOST_LOG_DIR}/zookeeper:${CONTAINER_LOG_DIR}

  kafka:
      image: skill-kafka
      build: ./kafka
      ports:
        - "${KAFKA_PORT}:9092"
      environment:
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
        KAFKA_ADVERTISED_PORT: "${KAFKA_PORT}"
        KAFKA_ZOOKEEPER_CONNECT: "${DOCKER_IP}:${ZOOKEEPER_PORT}"
#        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      volumes:
        - ${HOST_LOG_DIR}/kafka:${CONTAINER_LOG_DIR}
      depends_on:
      - zookeeper

  db:
      image: skill-db
      build: ./db
      ports:
      - "${DB_PORT}:5432"
      environment:
      - POSTGRES_PASSWORD=postgres
      volumes:
      - /tmp/skill/pgdata:${CONTAINER_PG_DATA}