#db:
#  image: postgres:latest
#  environment:
#    - POSTGRES_PASSWORD=project
#  restart: always
#
#skills:
##  image: dbarysevich/skills:latest
#  build: .
#  restart: always
#  links:
#    - db
#  ports:
#    - "8080:8080"
#  environment:
#    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#    - SPRING_DATASOURCE_USERNAME=postgres
#    - SPRING_DATASOURCE_PASSWORD=project
#    - SERVER_PORT=8080

version: '2'
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/24
services:

  db:
    image: skills-db
    build: ./db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data