SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET edb_redwood_date = off;
SET default_with_rowids = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

DROP SEQUENCE COMPANY_INFO_ID_SEQ;

CREATE SEQUENCE COMPANY_INFO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

SET default_with_oids = false;

DROP TABLE COMPANY_INFO;

CREATE TABLE COMPANY_INFO (
    id integer DEFAULT nextval('COMPANY_INFO_ID_SEQ') NOT NULL,
    name character varying(1000),
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    position_id integer
);

ALTER SEQUENCE COMPANY_INFO_ID_SEQ OWNED BY COMPANY_INFO;

DROP SEQUENCE ENVIRONMENT_ROW_ID_SEQ;

CREATE SEQUENCE ENVIRONMENT_ROW_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE ENVIRONMENT_ROW;
	
CREATE TABLE ENVIRONMENT_ROW (
    id integer DEFAULT nextval('ENVIRONMENT_ROW_ID_SEQ') NOT NULL,
    project_id integer,
    skill_id integer
);

ALTER SEQUENCE ENVIRONMENT_ROW_ID_SEQ OWNED BY ENVIRONMENT_ROW;

DROP SEQUENCE PERSON_ID_SEQ;

CREATE SEQUENCE PERSON_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE PERSON;
	
CREATE TABLE PERSON (
    id integer DEFAULT nextval('PERSON_ID_SEQ') NOT NULL,
    name character varying(1000)
);

ALTER SEQUENCE PERSON_ID_SEQ OWNED BY PERSON;

DROP SEQUENCE POSITION_ID_SEQ;

CREATE SEQUENCE POSITION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE POSITION;
	
CREATE TABLE POSITION (
    id integer DEFAULT nextval('POSITION_ID_SEQ') NOT NULL,
    name character varying(1000)
);

ALTER SEQUENCE POSITION_ID_SEQ OWNED BY POSITION;

DROP SEQUENCE PROJECT_ID_SEQ;

CREATE SEQUENCE PROJECT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE PROJECT;
	
CREATE TABLE PROJECT (
    id integer DEFAULT nextval('PROJECT_ID_SEQ') NOT NULL,
    position_id integer,
    description character varying,
    result character varying,
    responsibility character varying
);

ALTER SEQUENCE PROJECT_ID_SEQ OWNED BY PROJECT;

DROP SEQUENCE PROJECT_SUM_ID_SEQ;

CREATE SEQUENCE PROJECT_SUM_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE PROJECT_SUM;
	
CREATE TABLE PROJECT_SUM (
    id integer DEFAULT nextval('PROJECT_SUM_ID_SEQ') NOT NULL,
    person_id integer,
    project_id integer,
    company_id integer
);

ALTER SEQUENCE PROJECT_SUM_ID_SEQ OWNED BY PROJECT_SUM;

DROP SEQUENCE ROW_ID_SEQ;

CREATE SEQUENCE ROW_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE ROW;
	
CREATE TABLE ROW (
    id integer DEFAULT nextval('ROW_ID_SEQ') NOT NULL,
    name character varying(100)
);

ALTER SEQUENCE ROW_ID_SEQ OWNED BY ROW;

DROP SEQUENCE SKILL_ID_SEQ;

CREATE SEQUENCE SKILL_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE SKILL;
	
CREATE TABLE SKILL (
    id integer DEFAULT nextval('SKILL_ID_SEQ') NOT NULL,
    name character varying(100)
);

ALTER SEQUENCE SKILL_ID_SEQ OWNED BY SKILL;

DROP SEQUENCE SKILL_ROW_LINK_ID_SEQ;

CREATE SEQUENCE SKILL_ROW_LINK_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE SKILL_ROW_LINK;
	
CREATE TABLE SKILL_ROW_LINK (
    id integer DEFAULT nextval('SKILL_ROW_LINK_ID_SEQ') NOT NULL,
    skill_id integer,
    row_id integer,
    weight integer
);

ALTER SEQUENCE SKILL_ROW_LINK_ID_SEQ OWNED BY SKILL_ROW_LINK;

DROP SEQUENCE SKILL_SUM_ID_SEQ;

CREATE SEQUENCE SKILL_SUM_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE SKILL_SUM;
	
CREATE TABLE SKILL_SUM (
    id integer DEFAULT nextval('SKILL_SUM_ID_SEQ') NOT NULL,
    person_id integer,
    skill_row_id integer
);

ALTER SEQUENCE SKILL_SUM_ID_SEQ OWNED BY SKILL_SUM;

ALTER TABLE ONLY COMPANY_INFO
    ADD CONSTRAINT COMPANY_INFO_PK PRIMARY KEY (id);

ALTER TABLE ONLY ENVIRONMENT_ROW
    ADD CONSTRAINT ENVIRONMENT_PK PRIMARY KEY (id);

ALTER TABLE ONLY PERSON
    ADD CONSTRAINT PERSON_PK PRIMARY KEY (id);

ALTER TABLE ONLY POSITION
    ADD CONSTRAINT POSITION_PK PRIMARY KEY (id);

ALTER TABLE ONLY PROJECT
    ADD CONSTRAINT PROJECT_PK PRIMARY KEY (id);

ALTER TABLE ONLY PROJECT_SUM
    ADD CONSTRAINT PROJECT_SUM_PK PRIMARY KEY (id);

ALTER TABLE ONLY ROW
    ADD CONSTRAINT ROW_PK PRIMARY KEY (id);

ALTER TABLE ONLY SKILL
    ADD CONSTRAINT SKILL_PK PRIMARY KEY (id);

ALTER TABLE ONLY SKILL_ROW_LINK
    ADD CONSTRAINT SKILL_ROW_LINK_PK PRIMARY KEY (id);

ALTER TABLE ONLY SKILL_SUM
    ADD CONSTRAINT SKILL_SUM_PK PRIMARY KEY (id);

CREATE INDEX fki_COMPANY_INFO_POSITION_ID_FK ON COMPANY_INFO USING btree (position_id);

CREATE INDEX fki_ENVIRONMENT_ROW_PROJECT_ID_FK ON ENVIRONMENT_ROW USING btree (project_id);

CREATE INDEX fki_ENVIRONMENT_ROW_SKILL_ID ON ENVIRONMENT_ROW USING btree (skill_id);

CREATE INDEX fki_PROJECT_POSITION_ID_FK ON PROJECT USING btree (position_id);

CREATE INDEX fki_PROJECT_SUM_COMPANY_ID_FK ON PROJECT_SUM USING btree (company_id);

CREATE INDEX fki_PROJECT_SUM_PERSON_ID_FK ON PROJECT_SUM USING btree (person_id);

CREATE INDEX fki_PROJECT_SUM_PROJECT_ID_FK ON PROJECT_SUM USING btree (project_id);

CREATE INDEX fki_SKILL_ROW_LINK_ROW_ID_FK ON SKILL_ROW_LINK USING btree (row_id);

CREATE INDEX fki_SKILL_ROW_LINK_SKILL_ID ON SKILL_ROW_LINK USING btree (skill_id);

CREATE INDEX fki_SKILL_SUM_PERSON_ID_FK ON SKILL_SUM USING btree (person_id);

CREATE INDEX fki_SKILL_SUM_ROW_SKILL_ID_FK ON SKILL_SUM USING btree (skill_row_id);

ALTER TABLE ONLY COMPANY_INFO
    ADD CONSTRAINT COMPANY_INFO_POSITION_ID_FK FOREIGN KEY (position_id) REFERENCES POSITION(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY ENVIRONMENT_ROW
    ADD CONSTRAINT ENVIRONMENT_ROW_PROJECT_ID_FK FOREIGN KEY (project_id) REFERENCES PROJECT(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY ENVIRONMENT_ROW
    ADD CONSTRAINT ENVIRONMENT_ROW_SKILL_ID_FK FOREIGN KEY (skill_id) REFERENCES SKILL(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT
    ADD CONSTRAINT PROJECT_POSITION_ID_FK FOREIGN KEY (position_id) REFERENCES POSITION(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT_SUM
    ADD CONSTRAINT PROJECT_SUM_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES COMPANY_INFO(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT_SUM
    ADD CONSTRAINT PROJECT_SUM_PERSON_ID_FK FOREIGN KEY (person_id) REFERENCES PERSON(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY PROJECT_SUM
    ADD CONSTRAINT PROJECT_SUM_PROJECT_ID_FK FOREIGN KEY (project_id) REFERENCES PROJECT(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_ROW_LINK
    ADD CONSTRAINT SKILL_ROW_LINK_ROW_ID_FK FOREIGN KEY (row_id) REFERENCES ROW(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_ROW_LINK
    ADD CONSTRAINT SKILL_ROW_LINK_SKILL_ID_FK FOREIGN KEY (skill_id) REFERENCES SKILL(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_SUM
    ADD CONSTRAINT SKILL_SUM_PERSON_ID_FK FOREIGN KEY (person_id) REFERENCES PERSON(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY SKILL_SUM
    ADD CONSTRAINT SKILL_SUM_ROW_SKILL_ID_FK FOREIGN KEY (skill_row_id) REFERENCES SKILL_ROW_LINK(id) ON UPDATE CASCADE ON DELETE RESTRICT;
