SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET edb_redwood_date = OFF;
SET default_with_rowids = OFF;
SET check_function_bodies = FALSE;
SET client_min_messages = WARNING;
SET row_security = OFF;
SET default_with_oids = FALSE;

DROP TABLE PROJECT_SUM;
DROP TABLE SKILL_SUM;
DROP TABLE PERSON;
DROP TABLE ENVIRONMENT_ROW;
DROP TABLE PROJECT;
DROP TABLE ROW;
DROP TABLE COMPANY_INFO;
DROP TABLE SKILL;
DROP TABLE POSITION;
DROP TABLE DEPARTMENT;

DROP SEQUENCE COMPANY_INFO_ID_SEQ;
DROP SEQUENCE DEPARTMENT_ID_SEQ;
DROP SEQUENCE ENVIRONMENT_ROW_ID_SEQ;
DROP SEQUENCE PERSON_ID_SEQ;
DROP SEQUENCE POSITION_ID_SEQ;
DROP SEQUENCE PROJECT_ID_SEQ;
DROP SEQUENCE PROJECT_SUM_ID_SEQ;
DROP SEQUENCE ROW_ID_SEQ;
DROP SEQUENCE SKILL_ID_SEQ;
DROP SEQUENCE SKILL_SUM_ID_SEQ;

CREATE SEQUENCE DEPARTMENT_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE DEPARTMENT (
  id   INTEGER DEFAULT nextval('DEPARTMENT_ID_SEQ' :: REGCLASS) NOT NULL,
  name CHARACTER VARYING(500)                                   NOT NULL
);

ALTER SEQUENCE DEPARTMENT_ID_SEQ OWNED BY DEPARTMENT;

CREATE SEQUENCE COMPANY_INFO_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE COMPANY_INFO (
  id          INTEGER DEFAULT nextval('COMPANY_INFO_ID_SEQ') NOT NULL,
  name        CHARACTER VARYING(1000)                        NOT NULL,
  start_date  TIMESTAMP WITHOUT TIME ZONE,
  end_date    TIMESTAMP WITHOUT TIME ZONE,
  position_id INTEGER,
  deleted     SMALLINT                                       NOT NULL DEFAULT 0
);

ALTER SEQUENCE COMPANY_INFO_ID_SEQ OWNED BY COMPANY_INFO;

CREATE SEQUENCE ENVIRONMENT_ROW_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE ENVIRONMENT_ROW (
  id         INTEGER DEFAULT nextval('ENVIRONMENT_ROW_ID_SEQ') NOT NULL,
  project_id INTEGER,
  skill_id   INTEGER
);

ALTER SEQUENCE ENVIRONMENT_ROW_ID_SEQ OWNED BY ENVIRONMENT_ROW;

CREATE SEQUENCE PERSON_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE PERSON (
  id            INTEGER DEFAULT nextval('PERSON_ID_SEQ') NOT NULL,
  name          CHARACTER VARYING(1000)                  NOT NULL,
  department_id INTEGER,
  position_id   INTEGER,
  deleted       SMALLINT                                 NOT NULL DEFAULT 0,
  birth_date    DATE
);

ALTER SEQUENCE PERSON_ID_SEQ OWNED BY PERSON;

CREATE SEQUENCE POSITION_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE POSITION (
  id   INTEGER DEFAULT nextval('POSITION_ID_SEQ') NOT NULL,
  name CHARACTER VARYING(1000)                    NOT NULL
);

ALTER SEQUENCE POSITION_ID_SEQ OWNED BY POSITION;

CREATE SEQUENCE PROJECT_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE PROJECT (
  id             INTEGER DEFAULT nextval('PROJECT_ID_SEQ') NOT NULL,
  position_id    INTEGER,
  description    CHARACTER VARYING,
  result         CHARACTER VARYING,
  responsibility CHARACTER VARYING,
  deleted        SMALLINT                                  NOT NULL DEFAULT 0
);

ALTER SEQUENCE PROJECT_ID_SEQ OWNED BY PROJECT;

CREATE SEQUENCE PROJECT_SUM_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE PROJECT_SUM (
  id         INTEGER DEFAULT nextval('PROJECT_SUM_ID_SEQ') NOT NULL,
  person_id  INTEGER,
  project_id INTEGER,
  company_id INTEGER
);

ALTER SEQUENCE PROJECT_SUM_ID_SEQ OWNED BY PROJECT_SUM;

CREATE SEQUENCE ROW_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE ROW (
  id   INTEGER DEFAULT nextval('ROW_ID_SEQ') NOT NULL,
  name CHARACTER VARYING(100)                NOT NULL
);

ALTER SEQUENCE ROW_ID_SEQ OWNED BY ROW;

CREATE SEQUENCE SKILL_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE SKILL (
  id   INTEGER DEFAULT nextval('SKILL_ID_SEQ') NOT NULL,
  name CHARACTER VARYING(100)                  NOT NULL
);

ALTER SEQUENCE SKILL_ID_SEQ OWNED BY SKILL;

CREATE SEQUENCE SKILL_SUM_ID_SEQ
START WITH 1000
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE SKILL_SUM (
  id        INTEGER DEFAULT nextval('SKILL_SUM_ID_SEQ') NOT NULL,
  person_id INTEGER,
  skill_id  INTEGER,
  row_id    INTEGER,
  weight    INTEGER
);

ALTER SEQUENCE SKILL_SUM_ID_SEQ OWNED BY SKILL_SUM;

ALTER TABLE ONLY DEPARTMENT
  ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (id);

ALTER TABLE ONLY COMPANY_INFO
  ADD CONSTRAINT COMPANY_INFO_PK PRIMARY KEY (id);

ALTER TABLE ONLY ENVIRONMENT_ROW
  ADD CONSTRAINT ENVIRONMENT_PK PRIMARY KEY (id);

ALTER TABLE ONLY PERSON
  ADD CONSTRAINT PERSON_PK PRIMARY KEY (id);

ALTER TABLE ONLY POSITION
  ADD CONSTRAINT POSITION_PK PRIMARY KEY (id);

ALTER TABLE ONLY PROJECT
  ADD CONSTRAINT PROJECT_PK PRIMARY KEY (id);

ALTER TABLE ONLY PROJECT_SUM
  ADD CONSTRAINT PROJECT_SUM_PK PRIMARY KEY (id);

ALTER TABLE ONLY ROW
  ADD CONSTRAINT ROW_PK PRIMARY KEY (id);

ALTER TABLE ONLY SKILL
  ADD CONSTRAINT SKILL_PK PRIMARY KEY (id);

ALTER TABLE ONLY SKILL_SUM
  ADD CONSTRAINT SKILL_SUM_PK PRIMARY KEY (id);

CREATE INDEX fki_COMPANY_INFO_POSITION_ID_FK
  ON COMPANY_INFO USING BTREE (position_id);

CREATE INDEX fki_ENVIRONMENT_ROW_PROJECT_ID_FK
  ON ENVIRONMENT_ROW USING BTREE (project_id);

CREATE INDEX fki_ENVIRONMENT_ROW_SKILL_ID
  ON ENVIRONMENT_ROW USING BTREE (skill_id);

CREATE INDEX fki_PERSON_POSITION_ID_FK
  ON PERSON USING BTREE (position_id);

CREATE INDEX fki_PERSON_DEPARTMENT_ID_FK
  ON PERSON USING BTREE (department_id);

CREATE INDEX fki_PROJECT_POSITION_ID_FK
  ON PROJECT USING BTREE (position_id);

CREATE INDEX fki_PROJECT_SUM_COMPANY_ID_FK
  ON PROJECT_SUM USING BTREE (company_id);

CREATE INDEX fki_PROJECT_SUM_PERSON_ID_FK
  ON PROJECT_SUM USING BTREE (person_id);

CREATE INDEX fki_PROJECT_SUM_PROJECT_ID_FK
  ON PROJECT_SUM USING BTREE (project_id);

CREATE INDEX fki_SKILL_SUM_ROW_ID_FK
  ON SKILL_SUM USING BTREE (row_id);

CREATE INDEX fki_SKILL_SUM_SKILL_ID
  ON SKILL_SUM USING BTREE (skill_id);

CREATE INDEX fki_SKILL_SUM_PERSON_ID_FK
  ON SKILL_SUM USING BTREE (person_id);

ALTER TABLE ONLY COMPANY_INFO
  ADD CONSTRAINT COMPANY_INFO_POSITION_ID_FK FOREIGN KEY (position_id) REFERENCES POSITION (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY ENVIRONMENT_ROW
  ADD CONSTRAINT ENVIRONMENT_ROW_PROJECT_ID_FK FOREIGN KEY (project_id) REFERENCES PROJECT (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY ENVIRONMENT_ROW
  ADD CONSTRAINT ENVIRONMENT_ROW_SKILL_ID_FK FOREIGN KEY (skill_id) REFERENCES SKILL (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PERSON
  ADD CONSTRAINT PERSON_POSITION_ID_FK FOREIGN KEY (position_id) REFERENCES POSITION (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PERSON
  ADD CONSTRAINT PERSON_DEPARTMENT_ID_FK FOREIGN KEY (department_id) REFERENCES DEPARTMENT (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT
  ADD CONSTRAINT PROJECT_POSITION_ID_FK FOREIGN KEY (position_id) REFERENCES POSITION (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT_SUM
  ADD CONSTRAINT PROJECT_SUM_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES COMPANY_INFO (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY PROJECT_SUM
  ADD CONSTRAINT PROJECT_SUM_PERSON_ID_FK FOREIGN KEY (person_id) REFERENCES PERSON (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY PROJECT_SUM
  ADD CONSTRAINT PROJECT_SUM_PROJECT_ID_FK FOREIGN KEY (project_id) REFERENCES PROJECT (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_SUM
  ADD CONSTRAINT SKILL_SUM_ROW_ID_FK FOREIGN KEY (row_id) REFERENCES ROW (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_SUM
  ADD CONSTRAINT SKILL_SUM_SKILL_ID_FK FOREIGN KEY (skill_id) REFERENCES SKILL (id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY SKILL_SUM
  ADD CONSTRAINT SKILL_SUM_PERSON_ID_FK FOREIGN KEY (person_id) REFERENCES PERSON (id) ON UPDATE CASCADE ON DELETE CASCADE;
